Feature/76/dynatraceslosupport
keptn-contrib/dynatrace-sli-service pull request #110
Opened 2020-11-23 12:05 UTC by grabnerandi

work in progress

2020-11-30 15:59 UTC, grabnerandi commented
closing #112 - you can now have SLIs on every level (service, stage & project) and they are correctly "merged/inherited" as described in the doc
closing #109 - Dynatrace API Responses are now better handled. When unexpected errors happen they will be logged correctly instead of resulting in a parsing error
closing #97 - Now supporting native Dynatrace SLO definitions for both dashboard parsing as well as introducing a query option in sli.yaml
closing #104  - will now include better logging which includes the actual query string that was sent to the dynatrace metrics api
closing #105 - will now produce a logoutput in case we default to one of the 4 core SLIs (error_rate, p90, ...)

2020-12-01 09:10 UTC, bacherfl requested changes
Overall the PR looks good! I just have a few minor comments

2020-12-01 09:10 UTC, bacherfl commented on cmd/main.go
> +	/* 	//
let's delete those lines instead of commenting them out

2020-12-01 09:10 UTC, bacherfl commented on cmd/main.go
> +		if labelName == "Problem URL" {
to be safe, i suggest to convert both strings to lower case, e.g. `if strings.ToLower(labelName) == "problem url"

2020-12-01 09:10 UTC, bacherfl commented on README.md
> -|   0.7.2    | keptncontrib/dynatrace-sli-service:0.7.0 |
We should keep this line and add a new line with  `0.7.2 -> dynatrace-sli-service:0.7.1`

2020-12-01 09:10 UTC, bacherfl commented on README.md
> +dynatrace-sli-provider*  in your SLI.yamlexecutes your query
typo: `SLI.yamlexecutes`

2020-12-01 09:10 UTC, bacherfl commented on pkg/common/common.go
> +	} else {
this `else {}` block can be removed

2020-12-01 09:10 UTC, bacherfl commented on pkg/common/common.go
> +	/* if err != nil {
let's remove this code instead of commenting it out

2020-12-01 09:49 UTC, bacherfl approved these changes
lgtm

2020-12-01 09:50 UTC, merged