Increase Test Coverage, Updated Doc, Feature Flags and Reduce Logging
keptn-contrib/dynatrace-sli-service pull request #89
Opened 2020-09-25 16:32 UTC by grabnerandi

This PR includes the following changes
1. Increased Test coverage as raised in #78 
2. Implemented new dynatrace.conf.yaml option to control dashboard query feature as discussed in #82 
3. Updated readme.md with more details on different use cases and explained dynatrace.conf.yaml
4. Reduced some unnecessary logging. Here though more log cleanup would be possible but this should be implemented using proper log level handling as described here - https://github.com/keptn/keptn/issues/2413

2020-09-28 12:05 UTC, christian-kreuzberger-dtx commented on pkg/lib/dynatrace/dynatrace.go
> +		return 0, fmt.Errorf("Error when fetching SLI config for %s %s\n", metric, err.Error())
ignoring this golint warning

2020-09-28 12:05 UTC, christian-kreuzberger-dtx commented on pkg/lib/dynatrace/dynatrace.go
> +			return 0, fmt.Errorf("error from Execute Metrics API Query: %s\n", err.Error())
ignoring this golint warning

2020-09-28 12:06 UTC, christian-kreuzberger-dtx commented on pkg/lib/dynatrace/dynatrace.go
> +		} else {
@grabnerandi Is this correct? Please take a look and drop the else block, if it's correct.

2020-09-28 12:07 UTC, christian-kreuzberger-dtx commented on pkg/lib/dynatrace/dynatrace.go
> +		return nil, fmt.Errorf("No valid response from metrics api!")
Ignore this

2020-09-29 11:21 UTC, bacherfl approved these changes
lgtm

2020-09-30 14:28 UTC, agrimmer commented
Does this PR implement https://github.com/keptn-contrib/dynatrace-sli-service/issues/90?
If so, with this feature a Keptn project-stage-service combination would not be mapped to one DT tenant anymore. Right?
Can you please elaborate on the use case?

2020-09-30 14:34 UTC, grabnerandi commented
Hi @agrimmer - yes - this also implements #90 but I dont think it changes anything from before. Before you could define the secret name the dynatrace-sli-service should be using in dtCreds as a single string. Now we are simply allowing you to also use the the same placeholders we allow you to use in SLI definitions. It would allow you to map to different tenants - but - the same is true if you would simply change the values in the dynatrace-secret between quality gate runs.

2020-09-30 14:42 UTC, agrimmer requested changes
Clarify https://github.com/keptn-contrib/dynatrace-sli-service/issues/90

2020-10-01 05:48 UTC, agrimmer commented
Am I right that now labels would allow to dynamically select different DT-tenants for one Keptn service?
If so, we have no fixed mapping anymore between a Keptn service in a stage and project to a DT-tenant.
We at least have to think about the consequences first.

2020-10-01 07:02 UTC, grabnerandi commented
HI @agrimmer - you are correct. Technically it is possible to switch between different tenants on the same project/stage/service combination if you are using e.g: $LABELs. There are use cases where it makes sense to use $LABEL.xxx as placeholder but as a general best practice I suggest to use e.g: $STAGE as placeholder. Here is an example
```
dtCrends: dynatrace-$STAGE
```

This dynatrace.conf.yaml will - depending on the stage - pick the correct dynatrace credentials, e.g: dynatrace-dev, dynatrace-staging, dynatrace-prod ... -> this is a very common use case and can now be easily implemented with these placeholders and eliminates the need to upload different dynatracce.conf.yaml's for each stage

2020-10-01 07:05 UTC, agrimmer approved these changes
@grabnerandi thanks for the explanations!

2020-10-02 06:25 UTC, merged

2020-10-02 06:27 UTC, agrimmer commented
@grabnerandi Can you please close all issues which have been resolved with this PR?